In [2]:
import numpy as np

# Step 1: Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Step 2: Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Step 3: Print the array shape
array_shape = reshaped_array.shape
print("Shape of the reshaped array:", array_shape)

# Step 4: Replace the maximum value in each row with 0
max_replaced_array = reshaped_array.copy()
for row in max_replaced_array:
    row[row == row.max()] = 0

print("Array after replacing the max value in each row with 0:")
print(max_replaced_array)

# Step 5: Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Print the 4x3 array
print("4x3 array:")
print(array_4x3)

# Print the shape, type, and data type of the 4x3 array
print("Shape of 4x3 array:", array_4x3.shape)
print("Type of 4x3 array:", type(array_4x3))
print("Data type of 4x3 array:", array_4x3.dtype)


Shape of the reshaped array: (3, 5)
Array after replacing the max value in each row with 0:
[[ 9  9  0  6  8]
 [ 7 13  0  2 12]
 [ 0  4 12 13  9]]
4x3 array:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape of 4x3 array: (4, 3)
Type of 4x3 array: <class 'numpy.ndarray'>
Data type of 4x3 array: int32


In [3]:
import numpy as np

# Define the square array
square_array = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(square_array)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:")
print(eigenvalues)

print("Right Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]
Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
import numpy as np

# Define the array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(array)

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:", diagonal_sum)


Sum of the diagonal elements: 4


In [1]:
import numpy as np

# Create the initial array with shape (3, 2)
array_3x2 = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to shape (2, 3)
array_2x3 = array_3x2.reshape((2, 3))

# Print the original and reshaped arrays
print("Original array (3x2):")
print(array_3x2)
print("\nReshaped array (2x3):")
print(array_2x3)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
